dj_profiles/urls.py
from django.urls import path, re_path

from .views import UserCreateView, UserAuthenticationView, UserLogoutView, ProfileDetailView
from .views import UserPasswordResetView, UserPasswordChangeView, UserPasswordResetConfirmView, user_activate

urlpatterns = [
    path('user-registration/', UserCreateView.as_view(), name='user_registration'),
    path('user-authentication/', UserAuthenticationView.as_view(), name='user_authentication'),
    path('user-logout/', UserLogoutView.as_view(), name='user_logout'),
    path('user-profile/<int:pk>/', ProfileDetailView.as_view(), name='user_profile'),
    path('user-password-change/', UserPasswordChangeView.as_view(), name='user_password_change'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            user_activate, name='activate_email'),
    path('user-password-reset/', UserPasswordResetView.as_view(), name='user_password_reset'),
    path('reset/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm')
]

dj_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dj_articles.urls')),
    path('profile/', include('dj_profiles.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dj_articles/models.py
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.urls import reverse_lazy

User = get_user_model()


class Category(models.Model):
    title = models.CharField('Название', unique=True, max_length=255)
    slug = models.SlugField('URL', unique=True, max_length=255)
    description = models.TextField('Описание', blank=True, null=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Tag(models.Model):
    title = models.CharField('Название', unique=True, max_length=65)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, blank=True, null=True, verbose_name='Категория')
    slug = models.SlugField('URL', unique=True, max_length=65)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'


class Article(models.Model):
    title = models.CharField('Название', max_length=255)
    slug = models.SlugField('URL', max_length=255, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор')
    category = models.ForeignKey(Category, blank=True, null=True, on_delete=models.SET_NULL, verbose_name='Категория')
    image = models.ImageField('Изображение', upload_to='article/%Y/', blank=True, null=True)
    text = models.TextField('Текст статьии')
    tags = models.ManyToManyField(Tag, blank=True, verbose_name='Теги')
    created = models.DateTimeField('Создано', auto_now_add=True)
    updated = models.DateTimeField('Обновлено', auto_now=True)
    reputation = models.ManyToManyField(User, blank=True, related_name='article_reputation', verbose_name='Репутация')
    comments = GenericRelation('dj_comments.Comment', object_id_field='object_id', content_type_field='source')

    def get_absolute_url(self):
        return reverse_lazy('article_detail', kwargs={'slug': self.slug})

    def get_update_url(self):
        return reverse_lazy('article_update', kwargs={'slug': self.slug})

    def get_delete_url(self):
        return reverse_lazy('article_delete', kwargs={'slug': self.slug})

    def __str__(self):
        return f'Статья: {self.title} | {self.author.name}'

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьии'
        ordering = ('-created',)

dj_profiles/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.core.mail import send_mail
from django.db import models
from django.db.models import signals
from django.utils import timezone

from .managers import UserManager
from .tasks import send_email_registration


class User(AbstractBaseUser, PermissionsMixin):
    """ Модель пользователя """
    email = models.EmailField('Электронная почта', max_length=150, unique=True)
    name = models.CharField('Отображаемое имя', max_length=150, unique=True)
    first_name = models.CharField('Имя', max_length=150)
    last_name = models.CharField('Фамилие', max_length=150)
    image = models.ImageField('Изображение', upload_to='profiles/', blank=True, null=True)
    date_birth = models.DateField('Дата рождения', auto_now=False, auto_now_add=False)
    is_staff = models.BooleanField('Статус администратора', default=False,
                                   help_text='Определяет, может ли пользователь войти на сайт администратора.')
    is_active = models.BooleanField('Статус активации', default=False,
                                    help_text='Определяет, является ли пользователь действительным')

    date_joined = models.DateTimeField('Дата присоединения', default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name', 'first_name', 'last_name', 'date_birth']

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def get_full_name(self):
        full_name = f'{self.first_name} {self.last_name}'
        return full_name.strip()

    def get_short_name(self):
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        send_mail(subject, message, from_email, [self.email], **kwargs)


def user_post_save(sender, instance, signal, *args, **kwargs):
    """ Подтверждение электронной почты. """
    if not instance.is_active and not instance.is_staff:
        send_email_registration.delay(instance.pk)


signals.post_save.connect(user_post_save, sender=User)

dj_profiles/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.forms import PasswordResetForm, SetPasswordForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm
from django.template import Template, Context

from .models import User
from .tasks import password_recovery


class UserCreateForm(UserCreationForm):
    """ Форма регистрации пользователя """

    class Meta:
        model = User
        fields = ('email', 'name', 'first_name', 'last_name', 'date_birth')
        widgets = {'date_birth': forms.DateInput(attrs={'type': 'date'})}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        template = Template('{% include "dj_profiles/include/user_create_help_text.html" %}')
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
            context = Context({'help_text': self.fields[field].help_text})
            self.fields[field].help_text = template.render(context)


class UserAuthenticationForm(AuthenticationForm):
    """ Форма авторизации пользователя """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control mb-3'


class UserChangeFormAdmin(UserChangeForm):
    """ Форма изменения данных пользователя """

    class Meta:
        model = User
        fields = ('name', 'first_name', 'last_name', 'date_birth')


class ProfileChangeForm(forms.ModelForm):
    """ Форма изменения данных пользователя """

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'date_birth', 'image')


class UserPasswordChangeForm(SetPasswordForm):
    """ Форма изменения пароля пользователя """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'autocomplate': 'off'
            })


class UserPasswordResetForm(PasswordResetForm):
    """ Форма сброса пароля """
    email = forms.EmailField(
        label='Электронная почта',
        max_length=255,
        widget=forms.EmailInput(attrs={'class': 'form-control', 'id': 'id_email', 'autocomplete': 'email'})
    )

    def send_mail(self, subject_template_name, email_template_name, context, from_email, to_email,
                  html_email_template_name=None):
        context['user'] = context['user'].id  # Для сериализации данных при передаче в функцию delay.
        password_recovery.delay(subject_template_name=subject_template_name,
                                email_template_name=email_template_name,
                                context=context, from_email=from_email, to_email=to_email,
                                html_email_template_name=html_email_template_name)


class UserPasswordResetConfirmForm(SetPasswordForm):
    """ Форма смены пароля """
    new_password1 = forms.CharField(
        label='Новый пароль',
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'autocomplete': 'new-password'}),
        strip=False,
        help_text=password_validation.password_validators_help_text_html(),
    )
    new_password2 = forms.CharField(
        label='Подтвердите пароль',
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'autocomplete': 'new-password'}))

dj_profiles/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordResetConfirmView
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView

from .forms import UserPasswordResetForm, UserPasswordResetConfirmForm
from .mixins import ProfileDetailMixin, UserCreateMixin, UserAuthenticationMixin, UserPasswordChangeMixin
from .services import user_activate_email

User = get_user_model()


class ProfileDetailView(ProfileDetailMixin, DetailView):
    """ Профиль пользователя | Изменение пользователя"""
    template_name = 'dj_profiles/user_profile.html'


class UserCreateView(UserCreateMixin, CreateView):
    """ Регистрация пользователя """
    template_name = 'dj_profiles/user_registration.html'
    success_url = reverse_lazy('administrative_panel')


class UserAuthenticationView(UserAuthenticationMixin, LoginView):
    """ Авторизация пользователя """
    template_name = 'dj_profiles/user_authentication.html'
    success_url = reverse_lazy('administrative_panel')


class UserLogoutView(LogoutView):
    """ Выход пользователя """
    model = User
    next_page = reverse_lazy('article_list')


class UserPasswordChangeView(LoginRequiredMixin, UserPasswordChangeMixin, PasswordChangeView):
    """ Изменение пароля пользователя """
    login_url = reverse_lazy('user_authentication')
    template_name = 'dj_profiles/user_change_password.html'
    extra_context = {'title': 'Изменение пароля'}


class UserPasswordResetView(SuccessMessageMixin, PasswordResetView):
    """ Восстановление пароля пользователя """
    template_name = 'dj_profiles/user_change_password.html'
    form_class = UserPasswordResetForm
    success_url = reverse_lazy('user_authentication')
    success_message = 'Мы отправили вам инструкцию по установке нового пароля на указанный адрес электронной почты ' \
                      'Вы должны получить ее в ближайшее время.Если вы не получили письмо, пожалуйста, убедитесь, ' \
                      'что вы ввели адрес с которым Вы зарегистрировались, и проверьте папку со спамом.'


class UserPasswordResetConfirmView(SuccessMessageMixin, PasswordResetConfirmView):
    """ Ввод нового пароля пользователя """
    form_class = UserPasswordResetConfirmForm
    template_name = 'dj_profiles/user_change_password.html'
    success_url = reverse_lazy('user_authentication')
    success_message = 'Пароль успешно изменен!'


def user_activate(request, uidb64, token):
    user_activate_email(request, uidb64, token)
    return redirect(reverse_lazy('user_authentication'))

dj_profiles/templates/dj_profiles/user_authentication.html
{% extends 'base.html' %}
{% block title %} Авторизация пользователя {% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4 ">
            <h3 class="text-center mb-3"> Авторизация </h3>
            {% if messages %}
            {% for message in messages %}
            <div {% if message.tags %} class="alert alert-{{ message.tags }} text-center" {% endif %}>{{ message }}
            </div>
            {% endfor %}
            {% endif %}
            <form id="user-authentication" action="" method="POST">
                {% csrf_token %}
                {{ form }}
                <div class="d-grid gap-2">
                    <button class="btn btn-success" form="user-authentication">Авторизация</button>
                </div>
                <h6 class="text-center mt-3">
                    <a class="link-primary" href="{% url 'user_password_reset' %}">Забыли пароль?</a>
                </h6>
            </form>
        </div>
        <div class="col-4"></div>
    </div>
</div>
{% endblock %}

dj_profiles/templates/dj_profiles/user_change_password.html
{% extends 'base.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <h3 class="text-center"> Изменение пароля </h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{form}}
                <div class="d-grid gap-2">
                    <button class="btn btn-success mt-3" type="submit">Изменить</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

dj_profiles/templates/dj_profiles/user_profile.html
{% extends 'base.html' %}

{% load static %}
{% load get_age %}

{% block title %} Профиль пользователя {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-7">
            <h3 class="text-center">Пользователь</h3>
            <div class="row">
                <div class="col-3">
                    {% if object.image %}
                    <img id="id_image" src="{{ object.image.url }}" class="float-start img-fluid img-thumbnail"
                         alt="...">
                    {% else %}
                    <img src="{% static 'dj_profiles/img/no_user.png' %}"
                         class="float-start img-fluid img-thumbnail" alt="...">
                    {% endif %}

                </div>
                <div class="col">
                    <div><b>Электронный адрес:</b>
                        <span id="id_email">{{ object.email }}</span>
                    </div>
                    <div><b>Отображаемое имя:</b> <span id="id_name">{{ object.name }}</span></div>
                    <div><b>Имя:</b>
                        <span id="id_first_name">{{ object.first_name }}</span>
                    </div>
                    <div><b>Фамилия:</b>
                        <span id="id_last_name">{{ object.last_name }}</span>
                    </div>
                    <div><b>Дата рождения:</b>
                        <span id="id_date_birth">{{ object.date_birth }}</span> ( {{ object.date_birth|get_age }} )
                    </div>
                    <div id="div_image"></div>
                </div>
            </div>
            <div class="ms-3 mt-6">
                <div>
                    <button id="userChange" class="btn btn-primary mt-3 mb-3">Редактировать</button>
                    <button hidden id="sendUserChange" class="btn btn-success mt-3 mb-3">Сохранить</button>
                </div>

            </div>
            <div class="ms-3">
                <a href="{% url 'user_password_change' %}" id="passwordChange" class="text-success">Изменить пароль</a>
            </div>


        </div>
        <div class="col-md-5">
            <h3 class="text-center">Статистика пользователя</h3>
            <div><b>Количество статей:</b> {{object.article_set.all.count}}</div>
            <div><b>Количество комментарий:</b> {{ object.comment_user.all.count}}</div>
        </div>
    </div>

</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/axios/1.2.3/axios.min.js"
        integrity="sha512-L4lHq2JI/GoKsERT8KYa72iCwfSrKYWEyaBxzJeeITM9Lub5vlTj8tufqYk056exhjo2QDEipJrg6zen/DDtoQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script type="module" src="{% static 'dj_profiles/js/user_change.js' %}"></script>
{% endblock %}

dj_profiles/templates/dj_profiles/user_registration.html
{% extends 'base.html' %}
{% block title %} Регистрация пользователя {% endblock %}
{% block content %}
<div class="container">
    <div class="col-4">
        <h3 class="text-center mb-3">Регистрация пользователя</h3>
        <form id="user-registration" action="" method="POST">
            {% csrf_token %}

            {{ form }}

            <div class="d-grid gap-2">
                <button form="user-registration" class="btn btn-success">Регистрация</button>
            </div>
        </form>
    </div>
</div>

{% endblock %}

dj_profiles/templates/dj_profiles/user_reset_password.html
{% extends 'base.html' %}

{% block title %} Сброс пароля {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-5">
            <h3 class="text-center"> Восстановление пароля </h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.email}}
                    <button class="btn btn-success mt-3" type="submit">Восстановить мой пароль</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}